  export const ThemeColors = [
    {classname: 'red', dispname: 'Red', hexcolor: '#F44336'},
    {classname: 'pink', dispname: 'Pink', hexcolor: '#E91E63'},
    {classname: 'purple', dispname: 'Purple', hexcolor: '#9C27B0'},
    {classname: 'deep-purple', dispname: 'Deep Purple', hexcolor: '#673AB7'},
    {classname: 'indigo', dispname: 'Indigo', hexcolor: '#3F51B5'},
    {classname: 'blue', dispname: 'Blue', hexcolor: '#2196F3'},
    {classname: 'light-blue', dispname: 'Light Blue', hexcolor: '#03A9F4'},
    {classname: 'cyan', dispname: 'Cyan', hexcolor: '#00BCD4'},
    {classname: 'teal', dispname: 'Teal', hexcolor: '#009688'},
    {classname: 'green', dispname: 'Green', hexcolor: '#4CAF50'},
    {classname: 'light-green', dispname: 'Light Green', hexcolor: '#8BC34A'},
    {classname: 'lime', dispname: 'Lime', hexcolor: '#CDDC39'},
    {classname: 'yellow', dispname: 'Yellow', hexcolor: '#FFEB3B'},
    {classname: 'amber', dispname: 'Amber', hexcolor: '#FFC107'},
    {classname: 'orange', dispname: 'Orange', hexcolor: '#FF9800'},
    {classname: 'deep-orange', dispname: 'Deep Orange', hexcolor: '#FF5722'},
    {classname: 'brown', dispname: 'brown', hexcolor: '#795548'},
    {classname: 'grey', dispname: 'Grey', hexcolor: '#9E9E9E'},
    {classname: 'blue-grey', dispname: 'Blue Grey', hexcolor: '#607D8B'},
    {classname: 'black', dispname: 'Black', hexcolor: '#000'},
  ]
